language: python

install:
  - pip install mkdocs-material

script:
  - mkdocs build --clean --strict

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: site
  on:
    branch: master
