site_name: retest docs
theme: readthedocs

nav:
  - Home: index.md
  - recheck:
    - 'How ignore works': 'recheck/how-ignore-works-in-recheck.md'
    - 'Location of the Golden Master files': 'recheck/location-of-the-golden-master-files.md'
    - 'Reuse Golden Master Files': 'recheck/reuse-golden-master-files.md'
  - recheck-web: 'recheck-web/home.md'
  - retest:
    - 'English': 'retest/en/index.md'
    - 'German': 'retest/de/index.md'
  - Misc:
    - 'Google Summer of Code': 'recheck/gsoc.md'
