site_name: retest docs

theme:
   name: "mkdocs"
   custom_dir: 'custom_theme/'
        
extra_css:
    - 'css/custom.css'

nav:
  - Home: index.md
  - recheck:
    - 'recheck/how-ignore-works-in-recheck.md'
    - 'recheck/location-of-the-golden-master-files.md'
    - 'recheck/reuse-golden-master-files.md'
  - recheck.cli:
    - 'recheck.cli/setup.md'
  - recheck-web:
    - 'recheck-web/properties.md'
    - 'recheck-web/contributor-information.md'
  - retest:
    - 'English': 'retest/en/index.md'
    - 'Deutsch': 'retest/de/index.md'
  - Misc:
    - 'Google Summer of Code': 'misc/gsoc.md'
